### ISSUE TITLE
Plz update Schema DB.

### ISSUE THREAD

**Issue by Axsedor** [SteamDatabase/SteamDatabaseBackend#10]

**Comment by Sarymian** [comment]
https://github.com/SteamDatabase/steamdb.info/blob/master/Database.sql
no table 'Store'
https://github.com/SteamDatabase/SteamDatabaseBackend/blob/master/Processors/AppProcessor.cs#L259

**Comment by aguynamedryan** [comment]
Are there any plans to update the schema?  It's about 2 years out of date.
