### ISSUE TITLE
Does not include early-access apps?

### ISSUE THREAD

**Issue by baylf2000** [SteamDatabase/SteamDatabaseBackend#19]
Thanks so much for publishing this awesome code.

I'm able to get the app running successfully, however my version does not seem to include apps in early access. For example, "ATLAS" (AppID 1006030) which has been in early access for about a month now does not appear in my database. It currently has 9,560 records in the "apps" table.

Is there something I'm doing wrong?

**Comment by xPaw** [comment]
You'll have to use full runs to fill it.

**Comment by baylf2000** [comment]
Is that using the "FullRun" option in settings.json?

I've tried running it with FullRun set to 1, 4 and 5. Is that all I need to do in order to use full runs?

**Comment by xPaw** [comment]
These should work, yeah.
