### ISSUE TITLE
Maybe document the `settings.json`

### ISSUE THREAD

**Issue by 1yzz** [SteamDatabase/SteamDatabaseBackend#20]
want to know what's needed to make it run

**Comment by xPaw** [comment]
There's an example settings file already.

**Comment by 1yzz** [comment]
just like what does `"FullRun": 0,` means

**Comment by 1yzz** [comment]
`WebAPIKey` is needed for certain apis, not all of them as i know.

**Comment by 1yzz** [comment]
and is there a way to get history data just like price_overview. I googled this for a while , and that api seems to be closed by steam.

**Comment by 1yzz** [comment]
Anyway, Steamdb.info is a great tool that i'd like to use it every a few days. And this is a great project. Thanks
